changelog:
  exclude:
    labels:
      - tagpr
<<<<<<< HEAD
=======
  categories:
    - title: Breaking Changes ðŸ› 
      labels:
        - major
        - "breaking change"
    - title: Exciting New Features ðŸŽ‰
      labels:
        - minor
        - enhancement
    - title: Bug Fix ðŸ›
      labels:
        - bugfix
    - title: Other Changes
      labels:
        - "*"
>>>>>>> parent of 1691074 (add new release ci)
