name: push container image

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

  workflow_dispatch: {}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: ko-build/setup-ko@v0.6

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5

      - run: ko publish --bare --tags "${{ steps.meta.outputs.tags }},latest" ./cmd/prel

      - name: Update Release Body
        # when ref is a tag, github.ref is like refs/tags/v1.0.0
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          RELEASE_ID="${{ github.ref }}"
          BODY=$(gh release view ${RELEASE_ID} --json body -q '.body')
          IMAGE="ghcr.io/lirlia/prel:${RELEASE_ID}"
          NEW_BODY="${BODY}\n\n## Container Image\n\n\`\`\`bash\ndocker pull ${IMAGE}\n\`\`\`"

          gh release edit "$RELEASE_ID" --body "$NEW_BODY"

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
